[project]
name = "tiny-learning-dynamics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.1.1",
    "datasets>=3.1.0",
    "matplotlib>=3.9.2",
    "torch>=2.5.1",
    "transformers>=4.46.3",
]
